name: Sign Firmware

on:
  push:
    branches: ["main"]
    paths:
      - '**/*.bin'

jobs:
  sign:
    if: github.event.head_commit.message == 'Unsigned Firmware'
    runs-on: ubuntu-latest
    
    steps:
      # ---------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4
      # ---------------------------------

      - name: Firmware signin action
        uses: adishvx/unSigned@1.0.0
        # uses: apandey159/unsigned@1.0.0
        with:
          imt-token: ${{ secrets.IMT_TOKEN }}
          sign-key: ${{ secrets.SIGN_KEY }}
